import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import classes from '../classes.ts'

export default function Home() {

  const classList = (classes) => {
    for( let i = 0; i<classes.length-1; i++){
      console.log(classes[i].subjectDescription)
    }
  }

  classList(classes);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-slate-400 w-screen h-100'>
        
      </main>
    </div>
  )
}
