import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import classes from "../classes.ts";
export default function Home() {
  // const classList = (classes) => {
  //   let classesList
  //   for( let i = 0; i<classes.length-1; i++){
  //      classesList = classes[i].subjectDescription
  //   }
  //   return classesList
  // }

  // const classFun = classList(classes);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className="flex justify-between">
          <h1 className="bg-indigo-700 text-white rounded p-2 m-2">WITappa</h1>
          <nav className=" text-white m-2">
            <ul className="flex flex-row ">
              <li className="bg-indigo-700 rounded p-2 m-2">
                Login
              </li>
              <li className="bg-indigo-700 rounded p-2 m-2">
                About
              </li>
            </ul>
          </nav>
        </header>
        <section className="bg-slate-400 w-screen h-100">
          {classes.map((item) => {
                return (
                  <ul>
                    <li> </li>
                    <li>{item.courseTitle}</li>
                    <li>Prof: {item.faculty[0] ? item.faculty[0].displayName : ''}</li>
                    <li> </li>
                  </ul>
                );
              })}
        </section>
      </main>

    </div>
  );
}
